[package]
name = "kms"
version = "4.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
log4rs = { version = "1.0.0", features = ["default", "gzip"] }
clap = "3.0.0-beta.2"
git-version = "0.3.4"
tonic = "0.4.1"
prost = "0.7.0"
tokio = { version = "1.4.0", features = ["full"] }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "v4.0.0" }
r2d2 = "0.8.9"
r2d2_sqlite = "0.17.0"
rusqlite = "0.24.2"
rpassword = "5.0.1"
libsm = "0.3.0"
efficient-sm2 = "0.1.3"
rand = "0.8.3"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1

