[package]
name = "kms"
version = "5.0.0"
authors = ["Rivtower Technologies <contact@rivtower.com>"]
license = "Apache-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
log4rs = { version = "*", features = ["default", "gzip"] }
clap = "3.0.0-beta.2"
git-version = "*"
tonic = "*"
prost = "*"
tokio = { version = "*", features = ["full"] }
cita_cloud_proto = { git = "https://github.com/cita-cloud/cita_cloud_proto", branch = "full_block_develop" }
r2d2 = "*"
r2d2_sqlite = "*"
rusqlite = "*"
rpassword = "*"
libsm = "0.4.0"
efficient-sm2 = { git = "https://github.com/Pencil-Yao/efficient-sm2" }
rand = "0.8"

[profile.release.package."*"]
# Set the default for dependencies.
debug = 0

[profile.release]
# Add debug info -- line tables only
debug = 1
